{{- if and .Values.authService.enabled .Values.authService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "coxda-chart.fullname" . }}-auth
  labels:
    {{- include "coxda-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "coxda-chart.fullname" . }}-auth
  minReplicas: {{ .Values.authService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.authService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.authService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
