{{- if or .Values.authService.enabled .Values.commonService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coxda-chart.fullname" . }}-secret
  labels:
    {{- include "coxda-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Auth Service Secrets
  AUTH_APP_KEY: {{ .Values.authService.secrets.appKey | quote }}
  AUTH_JWT_SECRET: {{ .Values.authService.secrets.jwtSecret | quote }}
  AUTH_DB_USERNAME: {{ .Values.authService.secrets.dbUsername | quote }}
  AUTH_DB_PASSWORD: {{ .Values.authService.secrets.dbPassword | quote }}
  AUTH_REDIS_PASSWORD: {{ .Values.authService.secrets.redisPassword | quote }}

  # Common Service Secrets
  COMMON_APP_KEY: {{ .Values.commonService.secrets.appKey | quote }}
  COMMON_JWT_SECRET: {{ .Values.commonService.secrets.jwtSecret | quote }}
  COMMON_DB_USERNAME: {{ .Values.commonService.secrets.dbUsername | quote }}
  COMMON_DB_PASSWORD: {{ .Values.commonService.secrets.dbPassword | quote }}
  COMMON_REDIS_PASSWORD: {{ .Values.commonService.secrets.redisPassword | quote }}
{{- end }}
